# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
puts 'start to import'
official_users =[
  {"name"=>"Bruce Hung/洪暐銘", "user_number"=>"TW0009", "department"=>"BD"},
  {"name"=>"Hank Hsu/許恩漢", "user_number"=>"TW0010", "department"=>"MS"},
  {"name"=>"Paula Chin/金果諭", "user_number"=>"TW0015", "department"=>"MS"},
  {"name"=>"Ariel Huang/黃祥珍", "user_number"=>"TW0016", "department"=>"Acc"},
  {"name"=>"Michael Min/閔宇浩", "user_number"=>"TW0018", "department"=>"BD"},
  {"name"=>"Hsing Chi/紀幸汝", "user_number"=>"TW0020", "department"=>"MKT"},
  {"name"=>"Min Chih Chang/張敏芝", "user_number"=>"TW0024", "department"=>"MKT"},
  {"name"=>"Yoyo Chen/陳宥瑄", "user_number"=>"TW0026", "department"=>"MS"},
  {"name"=>"Roxy Chen/陳家瑜", "user_number"=>"TW0029", "department"=>"OP"},
  {"name"=>"Berton Chang/張嘉宏", "user_number"=>"TW0031", "department"=>"QA"},
  {"name"=>"Cooper Yang/楊皓詠", "user_number"=>"TW0032", "department"=>"QA"},
  {"name"=>"Ray Su/蘇嘉偉", "user_number"=>"TW0034", "department"=>"Eng"},
  {"name"=>"Cathy Xiong/熊育姍", "user_number"=>"TW0038", "department"=>"MKT"},
  {"name"=>"Rich Ke/柯秉承", "user_number"=>"TW0039", "department"=>"Eng"},
  {"name"=>"Erin Kan/甘家諭", "user_number"=>"TW0043", "department"=>"BD"},
  {"name"=>"Chiheng Lee/李其恆", "user_number"=>"TW0044", "department"=>"MS"},
  {"name"=>"Nana Syu/徐慧雯", "user_number"=>"TW0048", "department"=>"Eng"},
  {"name"=>"Kenny Chen/陳品瑜", "user_number"=>"TW0052", "department"=>"PTS"},
  {"name"=>"Stella Hsu/許嘉蘭", "user_number"=>"TW0054", "department"=>"PM"},
  {"name"=>"Vicky Hu/胡逸涵", "user_number"=>"TW0055", "department"=>"PM"},
  {"name"=>"Uma Chang/張瑜蓁", "user_number"=>"TW0058", "department"=>"BD"},
  {"name"=>"Peggy Li/李書霈", "user_number"=>"TW0059", "department"=>"BD"},
  {"name"=>"Regina Liu/劉汶芳", "user_number"=>"TW0067", "department"=>"QA"},
  {"name"=>"Jas Chen/陳冠宇", "user_number"=>"TW0068", "department"=>"Eng"},
  {"name"=>"Vivian Huang/黃亭瑋", "user_number"=>"TW0069", "department"=>"OP"},
  {"name"=>"Ellie Huang/黃筱婷", "user_number"=>"TW0070", "department"=>"Acc"},
  {"name"=>"Ian Wei/魏易安", "user_number"=>"TW0071", "department"=>"MKT"},
  {"name"=>"Connie Lee/李晏馨", "user_number"=>"TW0072", "department"=>"Project"},
  {"name"=>"Manson Hsieh/謝承勳", "user_number"=>"TW0076", "department"=>"Admin"},
  {"name"=>"Amanda Huang/黃子烜", "user_number"=>"TW0078", "department"=>"MS"},
  {"name"=>"Alvin Pan/潘國倫", "user_number"=>"TW0079", "department"=>"Eng"},
  {"name"=>"Vincent Wu/吳俊芃", "user_number"=>"TW0080", "department"=>"Eng"},
  {"name"=>"Gary Shen/沈福岳", "user_number"=>"TW0081", "department"=>"Eng"},
  {"name"=>"Carol Wang/王奕婷", "user_number"=>"TW0084", "department"=>"MS"},
  {"name"=>"Irene Lee/李彥儒", "user_number"=>"TW0086", "department"=>"QA"},
  {"name"=>"Kate Chuang/莊凱慈", "user_number"=>"TW0088", "department"=>"MS"},
  {"name"=>"Dennis Yao/姚順", "user_number"=>"TW0089", "department"=>"MS"},
  {"name"=>"Crystal Shih/施孟妤", "user_number"=>"TW0091", "department"=>"Acc"},
  {"name"=>"Alice Liu/劉慧慈", "user_number"=>"TW0092", "department"=>"BD"},
  {"name"=>"Catie Huang/黃鈺婷", "user_number"=>"TW0093", "department"=>"MS"},
  {"name"=>"Hsiaofan Hung/洪效凡", "user_number"=>"TW0094", "department"=>"MKT"},
  {"name"=>"Wei Liao/廖志偉", "user_number"=>"TW0095", "department"=>"MS"},
  {"name"=>"Ben Huang/黃胤翔", "user_number"=>"TW0098", "department"=>"Eng"},
  {"name"=>"Jordan Peng/彭子軒", "user_number"=>"TW0099", "department"=>"MKT"},
  {"name"=>"Chris Chang/張逸芳", "user_number"=>"TW0101", "department"=>"Acc"},
  {"name"=>"Jamie Chang/張婕敏", "user_number"=>"TW0102", "department"=>"Acc"},
  {"name"=>"Albee Li/李姿穎", "user_number"=>"TW0103", "department"=>"BD"},
  {"name"=>"Lawrence Lin/林家麒", "user_number"=>"TW0104", "department"=>"PM"},
  {"name"=>"Zora Chou/周佳樺", "user_number"=>"TW0105", "department"=>"QA"},
  {"name"=>"Carolyne Chen/陳凱柔", "user_number"=>"TW0106", "department"=>"MS"},
  {"name"=>"Cora Tseng/曾亞平", "user_number"=>"TW0107", "department"=>"PM"},
  {"name"=>"Adan Lin/林啓哲", "user_number"=>"TW0108", "department"=>"Eng"},
  {"name"=>"Roger Chang/張玉明", "user_number"=>"TW0109", "department"=>"Eng"},
  {"name"=>"Peter Wang/王孟濟", "user_number"=>"TW0110", "department"=>"BD"},
  {"name"=>"Yuna Chien/錢熙璇", "user_number"=>"TW0111", "department"=>"BD"},
  {"name"=>"Elvis Hsu/徐銘村", "user_number"=>"TW0113", "department"=>"Eng"},
  {"name"=>"June OuYang/歐陽倩如", "user_number"=>"TW0115", "department"=>"MKT"},
  {"name"=>"Darcy Teng/鄧苓", "user_number"=>"TW0116", "department"=>"MS"},
  {"name"=>"Ivan Wu/吳秉諭", "user_number"=>"TW0118", "department"=>"Eng"},
  {"name"=>"Miya Huang/黃惟莆", "user_number"=>"TW0119", "department"=>"Eng"},
  {"name"=>"Dennis Lu/盧奎明", "user_number"=>"TW0121", "department"=>"Eng"},
  {"name"=>"Dustin Lin/林星泓", "user_number"=>"TW0122", "department"=>"BD"},
  {"name"=>"Vivi Wang/王宜蓁", "user_number"=>"TW0123", "department"=>"QA"},
  {"name"=>"Blair Wang/王映婷", "user_number"=>"TW0124", "department"=>"MS"},
  {"name"=>"Meg Hou/侯妙樺", "user_number"=>"TW0127", "department"=>"MKT"},
  {"name"=>"Addison Tsai/蔡孟穎", "user_number"=>"TW0128", "department"=>"Acc"},
  {"name"=>"Berlin Yeh/葉柏伶", "user_number"=>"TW0129", "department"=>"MKT"},
  {"name"=>"Joanne Chen/陳嫶安", "user_number"=>"TW0130", "department"=>"PM"},
  {"name"=>"Allison Wang/王玉如", "user_number"=>"TW0131", "department"=>"HR"},
  {"name"=>"Amethyst Hong/洪彩媚", "user_number"=>"TW0133", "department"=>"QA"},
  {"name"=>"Chris Shao/邵保智", "user_number"=>"TW0135", "department"=>"Eng"},
  {"name"=>"Effie Kang/康嘉晏", "user_number"=>"TW0137", "department"=>"DATA"},
  {"name"=>"April Chang/張可柔", "user_number"=>"TW0139", "department"=>"MS"},
  {"name"=>"Sheryl Hsu/徐瑄佩", "user_number"=>"TW0141", "department"=>"Eng"},
  {"name"=>"Teresa Wang/王雯暄", "user_number"=>"TW0142", "department"=>"PM"},
  {"name"=>"Chloe Cheng/鄭宸鈺", "user_number"=>"TW0143", "department"=>"PM"},
  {"name"=>"Ruby Lai/賴奕儒", "user_number"=>"TW0145", "department"=>"MS"},
  {"name"=>"Simcoe Hsieh/謝沛宇", "user_number"=>"TW0147", "department"=>"Eng"},
  {"name"=>"Seminia Kung/孔貞貽", "user_number"=>"TW0148", "department"=>"MS"},
  {"name"=>"Tasmine Tsai/蔡羽婷", "user_number"=>"TW0149", "department"=>"MS"},
  {"name"=>"Winnie Tsai/蔡盼芸", "user_number"=>"TW0151", "department"=>"Acc"},
  {"name"=>"Karen Lin/林雨潔", "user_number"=>"TW0154", "department"=>"MS"},
  {"name"=>"Yin Hsiao/蕭穎晶", "user_number"=>"TW0156", "department"=>"Design"},
  {"name"=>"Ben Chuang/莊秉羲", "user_number"=>"TW0157", "department"=>"MS"},
  {"name"=>"Joyce Chen/陳怡婷", "user_number"=>"TW0159", "department"=>"BD"},
  {"name"=>"Max Chen/陳柏誠", "user_number"=>"TW0162", "department"=>"MS"},
  {"name"=>"Laura Lo/羅雅毓", "user_number"=>"TW0163", "department"=>"MKT"},
  {"name"=>"Alex Wang/王廷剛", "user_number"=>"TW0165", "department"=>"MS"},
  {"name"=>"Peiqi Teh/鄭佩棋", "user_number"=>"TW0166", "department"=>"CB"},
  {"name"=>"William Lin/林晧文", "user_number"=>"TW0167", "department"=>"Eng"},
  {"name"=>"Alyse Chen/陳郁旻", "user_number"=>"TW0170", "department"=>"MKT"},
  {"name"=>"Kai Yen/嚴凱泰", "user_number"=>"TW0172", "department"=>"MS"},
  {"name"=>"Linda Ho/何姿儀", "user_number"=>"TW0174", "department"=>"Eng"},
  {"name"=>"Bob Chen/陳柏豪", "user_number"=>"TW0175", "department"=>"QA"},
  {"name"=>"Elva Shen/沈予彤", "user_number"=>"TW0176", "department"=>"QA"},
  {"name"=>"Puffy Lin/林宜靜", "user_number"=>"TW0177", "department"=>"BD"},
  {"name"=>"Claire Hung/洪婉瑜", "user_number"=>"TW0178", "department"=>"PM"},
  {"name"=>"Velma Lee/李季薇", "user_number"=>"TW0182", "department"=>"BD"},
  {"name"=>"Sylvie Wang/王思懿", "user_number"=>"TW0183", "department"=>"Eng"},
  {"name"=>"Kellen Cheng/鄭勝宇", "user_number"=>"TW0184", "department"=>"Eng"},
  {"name"=>"Gene Pan/潘敬頤", "user_number"=>"TW0186", "department"=>"Eng"},
  {"name"=>"Lucia Chen/陳艾育", "user_number"=>"TW0188", "department"=>"BD"},
  {"name"=>"Bernice Yang/楊羽璇", "user_number"=>"TW0190", "department"=>"BD"},
  {"name"=>"Henry Chang/張博森", "user_number"=>"TW0192", "department"=>"BD"},
  {"name"=>"Lai/賴譽升", "user_number"=>"TW0194", "department"=>"BD"},
  {"name"=>"Ruth Lin/林倩如", "user_number"=>"TW0196", "department"=>"MKT"},
  {"name"=>"Gua Hsu/許啓哲", "user_number"=>"TW0197", "department"=>"Eng"},
  {"name"=>"Weiyi Lin/林惟一", "user_number"=>"TW0198", "department"=>"MKT"},
  {"name"=>"Berlina Chen/陳怡潔", "user_number"=>"TW0199", "department"=>"HR"},
  {"name"=>"Yichi Huang/黃苡齊", "user_number"=>"TW0200", "department"=>"MS"},
  {"name"=>"Susan Liao/廖偲涵", "user_number"=>"TW0201", "department"=>"MS"},
  {"name"=>"Eunice Chen/陳美光", "user_number"=>"TW0202", "department"=>"MS"},
  {"name"=>"Sandy Ho/何家琳", "user_number"=>"TW0203", "department"=>"MS"},
  {"name"=>"Patty Kao/高珮瑄", "user_number"=>"TW0204", "department"=>"QA"},
  {"name"=>"Hannah Zhuang/莊翊卉", "user_number"=>"TW0205", "department"=>"QA"},
  {"name"=>"Steven Lee/李昱宏", "user_number"=>"TW0206", "department"=>"PM"},
  {"name"=>"Kevin Wang/王建為", "user_number"=>"TW0207", "department"=>"Eng"},
  {"name"=>"Jennifer Yu/游以彤", "user_number"=>"TW0208", "department"=>"QA"},
  {"name"=>"Kelly Chang/張玉穎", "user_number"=>"TW0209", "department"=>"CS"},
  {"name"=>"Jared Lin/林冠達", "user_number"=>"TW0210", "department"=>"Eng"},
  {"name"=>"Theresa See/許芩瑜", "user_number"=>"TW0211", "department"=>"MS"},
  {"name"=>"Yvonne Wei/魏子琄", "user_number"=>"TW0212", "department"=>"OP"},
  {"name"=>"Queenie Chan/詹雅筑", "user_number"=>"TW0214", "department"=>"MS"},
  {"name"=>"Alan Chung/鍾培元", "user_number"=>"TW0217", "department"=>"MS"},
  {"name"=>"Joseph Lin/林昊宇", "user_number"=>"TW0218", "department"=>"MS"},
  {"name"=>"Gavin Lu/呂瑋強", "user_number"=>"TW0224", "department"=>"Eng"},
  {"name"=>"Tinny Wang/王韋庭", "user_number"=>"TW0225", "department"=>"Eng"},
  {"name"=>"Vicky Shih/施來欣", "user_number"=>"TW0226", "department"=>"MS"},
  {"name"=>"Daniel Tsay/蔡易達", "user_number"=>"TW0228", "department"=>"BD"},
  {"name"=>"Ian Lin/林彥均", "user_number"=>"TW0229", "department"=>"BD"},
  {"name"=>"Bill Huang/黃子濬", "user_number"=>"TW0231", "department"=>"Eng"},
  {"name"=>"Leon Ji/紀富升", "user_number"=>"TW0232", "department"=>"Eng"},
  {"name"=>"Joni Huang/黃中誼", "user_number"=>"TW0234", "department"=>"MS"},
  {"name"=>"Aris Wu/吳敏嘉", "user_number"=>"TW0236", "department"=>"BD"},
  {"name"=>"Jenny Pan/潘建寧", "user_number"=>"TW0237", "department"=>"MS"},
  {"name"=>"Sherry Hung/洪芷璿", "user_number"=>"TW0239", "department"=>"QA"},
  {"name"=>"Lester Wu/吳宗勳", "user_number"=>"TW0242", "department"=>"PTS"},
  {"name"=>"Allen Wang/王蔚豪", "user_number"=>"TW0243", "department"=>"HR"},
  {"name"=>"Cindy Lo/羅琬渝", "user_number"=>"TW0244", "department"=>"MS"},
  {"name"=>"Ian Chi/紀宜均", "user_number"=>"TW0245", "department"=>"DATA"},
  {"name"=>"Belinda Chang/張華宜", "user_number"=>"TW0248", "department"=>"MKT"},
  {"name"=>"Kevin Tsai/蔡凱倫", "user_number"=>"TW0250", "department"=>"QA"},
  {"name"=>"Alexander Chen/陳驥", "user_number"=>"TW0255", "department"=>"Eng"},
  {"name"=>"Andy Chuang/莊育棋", "user_number"=>"TW0256", "department"=>"Eng"},
  {"name"=>"Tina Chen/陳仕婷", "user_number"=>"TW0257", "department"=>"Design"},
  {"name"=>"Arthur Huang/黃耀慶", "user_number"=>"TW0258", "department"=>"Eng"},
  {"name"=>"Stella Chiang/江佳恬", "user_number"=>"TW0259", "department"=>"MKT"},
  {"name"=>"Heidi Lin/林靖芳", "user_number"=>"TW0260", "department"=>"MS"},
  {"name"=>"Annie Chang/張雅婷", "user_number"=>"TW0261", "department"=>"MS"},
  {"name"=>"Vivian Tsai/蔡瑋瑋", "user_number"=>"TW0262", "department"=>"QA"},
  {"name"=>"Chiaoan Yang/楊喬安", "user_number"=>"TW0263", "department"=>"Project"},
  {"name"=>"Chelsey Wang/王琦婷", "user_number"=>"TW0264", "department"=>"DATA"},
  {"name"=>"Sandrine Yen/嚴郁嫻", "user_number"=>"TW0265", "department"=>"Acc"},
  {"name"=>"Kevin Wu/吳家愷", "user_number"=>"TW0267", "department"=>"MKT"},
  {"name"=>"Edward Huang/黃彥豪", "user_number"=>"TW0268", "department"=>"PM"},
  {"name"=>"Willis Chou/周韋廷", "user_number"=>"TW0269", "department"=>"Eng"},
  {"name"=>"Kenneth Chen/陳郁文", "user_number"=>"TW0270", "department"=>"Eng"},
  {"name"=>"Cindy Kao/高宥家", "user_number"=>"TW0272", "department"=>"MKT"},
  {"name"=>"Emma Lin/林佳慧", "user_number"=>"TW0273", "department"=>"MS"},
  {"name"=>"Ariel Yih/易涵", "user_number"=>"TW0275", "department"=>"MKT"},
  {"name"=>"Joanna Cho/卓妤芳", "user_number"=>"TW0276", "department"=>"MS"},
  {"name"=>"Carol Chang/張䕒云", "user_number"=>"TW0277", "department"=>"MS"},
  {"name"=>"Angus Huang/黃于珊", "user_number"=>"TW0278", "department"=>"MS"},
  {"name"=>"Howard Chen/陳致濂", "user_number"=>"TW0279", "department"=>"HR"},
  {"name"=>"Quincey Peng/彭子瑜", "user_number"=>"TW0280", "department"=>"MKT"},
  {"name"=>"Kevin Chen/陳亮宇", "user_number"=>"TW0281", "department"=>"MKT"},
  {"name"=>"Ching Ching Lee/李晶晶", "user_number"=>"TW0283", "department"=>"DATA"},
  {"name"=>"Yee Yang Neo/梁宇揚", "user_number"=>"TW0284", "department"=>"MS"},
  {"name"=>"Riley Lin/林怡君", "user_number"=>"TW0285", "department"=>"MS"},
  {"name"=>"Eason Tseng/曾思豪", "user_number"=>"TW0286", "department"=>"MS"},
  {"name"=>"Chris Hsu/徐肇良", "user_number"=>"TW0287", "department"=>"MKT"},
  {"name"=>"Jack Lin/林育存", "user_number"=>"TW0289", "department"=>"CS"},
  {"name"=>"Claire Wu/吳旻珊", "user_number"=>"TW0291", "department"=>"MS"},
  {"name"=>"Mumu Wu/吳沐蓉", "user_number"=>"TW0293", "department"=>"BD"},
  {"name"=>"Vicky Shih/施佳惠", "user_number"=>"TW0294", "department"=>"QA"},
  {"name"=>"Stanley Chen/陳少勤", "user_number"=>"TW0295", "department"=>"GM"},
  {"name"=>"Alex Huang/黃梓宸", "user_number"=>"TW0297", "department"=>"QA"},
  {"name"=>"Linster Lin/林家宏", "user_number"=>"TW0298", "department"=>"Eng"},
  {"name"=>"Sandy Hsieh/謝怡儒", "user_number"=>"TW0299", "department"=>"OP"},
  {"name"=>"Lulu Liao/廖珮如", "user_number"=>"TW0300", "department"=>"CS"},
  {"name"=>"Eunice Lin/林芷薇", "user_number"=>"TW0301", "department"=>"MS"},
  {"name"=>"Jason Wang/王賀", "user_number"=>"TW0302", "department"=>"Eng"},
  {"name"=>"Lear Ho/何冠廷", "user_number"=>"TW0304", "department"=>"MS"},
  {"name"=>"Stacey Chen/陳雅潔", "user_number"=>"TW0305", "department"=>"Admin"},
  {"name"=>"Tony Fang/方秉彥", "user_number"=>"TW0306", "department"=>"PM"},
  {"name"=>"Katherine Lee/李惟", "user_number"=>"TW0307", "department"=>"Legal"},
  {"name"=>"Helen Chung/鍾采倫", "user_number"=>"TW0308", "department"=>"MKT"},
  {"name"=>"Jason Su/蘇子翔", "user_number"=>"TW0311", "department"=>"Eng"},
  {"name"=>"Amy Ku/古佳靜", "user_number"=>"TW0314", "department"=>"BD"},
  {"name"=>"Vera Chen/陳嘉慧", "user_number"=>"TW0316", "department"=>"BD"},
  {"name"=>"Peter Pan/潘國育", "user_number"=>"TW0318", "department"=>"Eng"},
  {"name"=>"Li Yi Yang/楊力怡", "user_number"=>"TW0319", "department"=>"Eng"},
  {"name"=>"Sanya Wang/王詩筑", "user_number"=>"TW0321", "department"=>"Acc"},
  {"name"=>"Trevor Tseng/曾永祥", "user_number"=>"TW0322", "department"=>"MKT"},
  {"name"=>"Lidia Chu/祝瑋翎", "user_number"=>"TW0323", "department"=>"BD"},
  {"name"=>"Zac Yeh/葉芯妤", "user_number"=>"TW0324", "department"=>"BD"},
  {"name"=>"Patrick Hsieh/謝宏培", "user_number"=>"TW0325", "department"=>"BD"},
  {"name"=>"Benson Cheng/鄭羽涵", "user_number"=>"TW0326", "department"=>"BD"},
  {"name"=>"Eva Chiu/邱盈華", "user_number"=>"TW0327", "department"=>"BD"},
  {"name"=>"Bonnie Sun/孫佳榕", "user_number"=>"TW0328", "department"=>"MKT"},
  {"name"=>"Connie Ma/馬康綺", "user_number"=>"TW0329", "department"=>"MKT"},
  {"name"=>"Nicole Wang/王立慧", "user_number"=>"TW0333", "department"=>"MS"},
  {"name"=>"Alex Wang/王慶良", "user_number"=>"TW0334", "department"=>"BD"},
  {"name"=>"Amelia Hsiao/蕭靜芸", "user_number"=>"TW0336", "department"=>"PTS"},
  {"name"=>"Joanne Huang/黃思媛", "user_number"=>"TW0337", "department"=>"MS"},
  {"name"=>"Nicole Wu/吳品萱", "user_number"=>"TW0338", "department"=>"MS"},
  {"name"=>"HsiangMin Yu/游詳閔", "user_number"=>"TW0340", "department"=>"PM"},
  {"name"=>"Vense Chang/張哲維", "user_number"=>"TW0341", "department"=>"Eng"},
  {"name"=>"Boxi Li/李柏希", "user_number"=>"TW0342", "department"=>"Eng"},
  {"name"=>"Nancy Lin/林筱融", "user_number"=>"TW0343", "department"=>"DATA"},
  {"name"=>"Serena Lai/賴珮雯", "user_number"=>"TW0344", "department"=>"Eng"},
  {"name"=>"Sunny Pham/范明日", "user_number"=>"TW0345", "department"=>"MKT"},
  {"name"=>"Jess Pham/范香江", "user_number"=>"TW0346", "department"=>"MKT"},
  {"name"=>"Abby Li/李宜樺", "user_number"=>"TW0347", "department"=>"BD"},
  {"name"=>"Hannah Huang/黃若涵", "user_number"=>"TW0348", "department"=>"BD"},
  {"name"=>"Tim Kuo/郭庭甫", "user_number"=>"TW0349", "department"=>"BD"},
  {"name"=>"Tank Lin/林侑延", "user_number"=>"TW0350", "department"=>"Eng"},
  {"name"=>"Frank Liao/廖哲偉", "user_number"=>"TW0351", "department"=>"Eng"},
  {"name"=>"Jiajia Yurawan/陳佳恩", "user_number"=>"TW0352", "department"=>"MKT"},
  {"name"=>"Angela Hung/洪子涵", "user_number"=>"TW0353", "department"=>"DATA"},
  {"name"=>"Bart Lai/賴耀弘", "user_number"=>"TW0355", "department"=>"QA"},
  {"name"=>"Kevyn Huang/黃楷雯", "user_number"=>"TW0356", "department"=>"MKT"},
  {"name"=>"Zoe Kung/龔柔宇", "user_number"=>"TW0357", "department"=>"MKT"},
  {"name"=>"Glenn Ung/翁東彬", "user_number"=>"TW0358", "department"=>"MKT"},
  {"name"=>"Mia Huang/黃千瑞", "user_number"=>"TW0359", "department"=>"MS"},
  {"name"=>"Michelle Chang/張秦敏", "user_number"=>"TW0361", "department"=>"MS"},
  {"name"=>"Soseon Wang/王筱嬋", "user_number"=>"TW0363", "department"=>"MS"},
  {"name"=>"Elly Liu/劉宛諭", "user_number"=>"TW0365", "department"=>"MS"},
  {"name"=>"Ariel Cai/蔡子涵", "user_number"=>"TW0367", "department"=>"BD"},
  {"name"=>"Wayne Pan/潘有為", "user_number"=>"TW0368", "department"=>"MKT"},
  {"name"=>"Katie Chan/詹仁瑜", "user_number"=>"TW0369", "department"=>"MS"},
  {"name"=>"Leila Lu/呂宜玲", "user_number"=>"TW0370", "department"=>"BD"},
  {"name"=>"Shelly Chang/張宜靜", "user_number"=>"TW0371", "department"=>"MKT"},
  {"name"=>"Eric Cheng/鄭於青", "user_number"=>"TW0372", "department"=>"Eng"},
  {"name"=>"Alice Hsieh/謝佳軒", "user_number"=>"TW0373", "department"=>"Acc"},
  {"name"=>"Ken Shih/施凱恩", "user_number"=>"TW0375", "department"=>"MS"},
  {"name"=>"Peter peng/彭柏臻", "user_number"=>"TW0376", "department"=>"MKT"},
  {"name"=>"Emma hsiao/蕭育青", "user_number"=>"TW0377", "department"=>"Acc"},
  {"name"=>"Beebe Weng/翁資琹", "user_number"=>"TW0378", "department"=>"MKT"},
  {"name"=>"Grimmy Chen/陳思穎", "user_number"=>"TW0381", "department"=>"MKT"},
  {"name"=>"Chiron Chang/張尹芝", "user_number"=>"TW0383", "department"=>"BD"},
  {"name"=>"Tim Chen/陳昱霖", "user_number"=>"TW0385", "department"=>"Eng"},
  {"name"=>"Christine Ma/馬政琪", "user_number"=>"TW0386", "department"=>"PM"},
  {"name"=>"Ting Tsai/蔡儀亭", "user_number"=>"TW0387", "department"=>"MKT"},
  {"name"=>"Sylvia Lo/羅少翎", "user_number"=>"TW0389", "department"=>"OP"},
  {"name"=>"Emma Liu/柳家芸", "user_number"=>"TW0390", "department"=>"MS"},
  {"name"=>"Alice Yen/顏小珉", "user_number"=>"TW0391", "department"=>"OP"},
  {"name"=>"Jenny Kao/高永真", "user_number"=>"TW0392", "department"=>"MKT"},
  {"name"=>"Jessie Chang/張道芳", "user_number"=>"TW0393", "department"=>"PM"},
  {"name"=>"Laura Chiang/姜文惠", "user_number"=>"TW0394", "department"=>"BD"},
  {"name"=>"Daniel Huang/黃晨誌", "user_number"=>"TW0395", "department"=>"BD"},
  {"name"=>"Jasmie Chiu/邱莉婷", "user_number"=>"TW0397", "department"=>"MS"},
  {"name"=>"Ting Ng/吳浩廷", "user_number"=>"TW0398", "department"=>"Eng"},
  {"name"=>"Elisa Lu/呂怡儒", "user_number"=>"TW0399", "department"=>"MS"},
  {"name"=>"Kelly Chang/張凱琳", "user_number"=>"TW0400", "department"=>"BD"},
  {"name"=>"Kami Chen/陳奕宏", "user_number"=>"TW0401", "department"=>"Eng"},
  {"name"=>"Wayne Wen/溫邦宇", "user_number"=>"TW0402", "department"=>"Eng"},
  {"name"=>"Sunny Kao/高千惠", "user_number"=>"TW0403", "department"=>"MKT"},
  {"name"=>"Will Chang/張瑋", "user_number"=>"TW0405", "department"=>"HR"},
  {"name"=>"Jimmy Cheng/鄭景仁", "user_number"=>"TW0406", "department"=>"Eng"},
  {"name"=>"Ivon Su/蘇盈霖", "user_number"=>"TW0407", "department"=>"Logistics"},
  {"name"=>"Loren Luo/羅安璇", "user_number"=>"TW0408", "department"=>"MKT"},
  {"name"=>"Jessica Li/李潔斯", "user_number"=>"TW0409", "department"=>"MS"},
  {"name"=>"Hannah Gao/高嘉涓", "user_number"=>"TW0410", "department"=>"QA"},
  {"name"=>"Sherry Hsu/徐嘉臨", "user_number"=>"TW0411", "department"=>"BD"},
  {"name"=>"Audrey Chin/金郁文", "user_number"=>"TW0412", "department"=>"BD"},
  {"name"=>"Yulissa Kuo/郭書妤", "user_number"=>"TW0413", "department"=>"BD"},
  {"name"=>"Laura Hsieh/謝芸軒", "user_number"=>"TW0415", "department"=>"MS"},
  {"name"=>"Iris Hsu/許雅婷", "user_number"=>"TW0416", "department"=>"Project"},
  {"name"=>"Fire Cheng/鄭有順", "user_number"=>"TW0417", "department"=>"Eng"},
  {"name"=>"Dande Aw Yong/歐陽靜儀", "user_number"=>"TW0418", "department"=>"PTS"},
  {"name"=>"Walle Liou/劉韶羽", "user_number"=>"TW0419", "department"=>"MS"},
  {"name"=>"Veronica Wang/王亭喬", "user_number"=>"TW1054", "department"=>"Eng"},
  {"name"=>"Sylvia Lee/李晶瀅", "user_number"=>"TW0421", "department"=>"PM"},
  {"name"=>"Mille Huang/黃千晉", "user_number"=>"TW0422", "department"=>"MKT"}
]
official_users.each do |data|
  user = User.create_or_find_by(user_number: data['user_number'])
  user.update!(name: data['name'], department: data['department'], drawable: true)
end
puts 'finished importing official_users'


new_users = [
  {"name"=>"TangYu Lin/林唐煜", "user_number"=>"TW0423", "department"=>"BD"},
  {"name"=>"Tim Yeh/葉炴廷", "user_number"=>"TW0424", "department"=>"BD"},
  {"name"=>"Max Huang/黃顯棠", "user_number"=>"TW0425", "department"=>"BD"},
  {"name"=>"Sonya Lin/林姝彣", "user_number"=>"TW0426", "department"=>"MS"},
  {"name"=>"Ruki Chiu/邱冠綺", "user_number"=>"TW0427", "department"=>"MS"},
  {"name"=>"Marcus Yeh/葉祐成", "user_number"=>"TW0428", "department"=>"MS"},
  {"name"=>"Maki Tsai/蔡宜真", "user_number"=>"TW0429", "department"=>"MKT"},
  {"name"=>"Eva Tsai/蔡怡芃", "user_number"=>"TW0430", "department"=>"MKT"},
  {"name"=>"Syu Syu/徐玉婷", "user_number"=>"TW0431", "department"=>"MKT"},
  {"name"=>"Adam Graudus/高亞當", "user_number"=>"TW0432", "department"=>"MKT"},
  {"name"=>"Momo Yang/楊芷瑀", "user_number"=>"TW0433", "department"=>"Acc"},
  {"name"=>"Sue Su/蘇郁茹", "user_number"=>"TW0434", "department"=>"MS"},
  {"name"=>"Jack Tsao/曹良愷", "user_number"=>"TW0435", "department"=>"MS"},
  {"name"=>"Rebecca Hsiho/蕭儀齡", "user_number"=>"TW0436", "department"=>"Design"},
  {"name"=>"Uriah Wu/吳秉瞬", "user_number"=>"QF0055", "department"=>"Eng"},
  {"name"=>"Chuck Lin/林旻延", "user_number"=>"QF0056", "department"=>"Eng"},
  {"name"=>"Walker Huang/黃軍皓", "user_number"=>"TW0437", "department"=>"MS"},
  {"name"=>"Ryan Huang/黃冠允", "user_number"=>"ST0001", "department"=>'Finance'},
  {"name"=>"Hank Tseng/曾繼漢", "user_number"=>"TW0439", "department"=>"BD"},
  {"name"=>"Hank Chen/陳凱璁", "user_number"=>"TW0440", "department"=>"Logistics"},
  {"name"=>"Ian Liao/廖翊宏", "user_number"=>"TW0441", "department"=>"MS"},
  {"name"=>"Russell Tsai/蔡松樺", "user_number"=>"QF0057", "department"=>"Eng"},
  {"name"=>"Reina Pai/白惠瑄", "user_number"=>"TW0442", "department"=>"MKT"},
  {"name"=>"Eva Tsou/鄒惠萍", "user_number"=>"TW0443", "department"=>"MKT"},
  {"name"=>"Jolly Wang/王偉馨", "user_number"=>"TW0444", "department"=>"MS"},
  {"name"=>"You Cheng Hsu/許祐誠", "user_number"=>"QF0058", "department"=>"Eng"},
  {"name"=>"Alice Chin/秦子晴", "user_number"=>"TW0445", "department"=>"HR"},
  {"name"=>"Bob Chen/陳柏宇", "user_number"=>"TW0446", "department"=>"MKT"},
  {"name"=>"Velisa Zhong/鍾雅璇", "user_number"=>"TW0447", "department"=>"MKT"},
  {"name"=>"Faith Lu/呂怡玫", "user_number"=>"TW0448", "department"=>"PM"},
  {"name"=>"Sam Liu/劉宇晨", "user_number"=>"TW0449", "department"=>"BD"},
  {"name"=>"Annie Lee/李瑞瑄", "user_number"=>"TW0450", "department"=>"BD"},
  {"name"=>"Angel Li/李奕璇", "user_number"=>"TW0451", "department"=>"DATA"},
  {"name"=>"Alan Yang/楊卓儒", "user_number"=>"TW0452", "department"=>"DATA"},
  {"name"=>"Jesse Yang/楊捷旭", "user_number"=>"QF0059", "department"=>"Eng"},
  {"name"=>"Karen Yu/余育寧", "user_number"=>"TW0453", "department"=>"MKT"},
  {"name"=>"Damon Tsai/蔡孟勳", "user_number"=>"TW0454", "department"=>"MKT"},
  {"name"=>"Cyndi Chang/張家馨", "user_number"=>"TW0455", "department"=>"MKT"},
  {"name"=>"Kai Lin/林凱強", "user_number"=>"TW0456", "department"=>"MKT"},
  {"name"=>"Mini Chen/陳苡君", "user_number"=>"TW0457", "department"=>"BD"},
  {"name"=>"Stan Tseng/曾薰儀", "user_number"=>"TW0458", "department"=>"Admin"},
  {"name"=>"Elmer Zhu/朱哲呈", "user_number"=>"TW0459", "department"=>"MS"},
  {"name"=>"Emma Huang/黃慧汶", "user_number"=>"TW0460", "department"=>"MS"},
  {"name"=>"Eddie Tang/唐維良", "user_number"=>"TW0461", "department"=>"MS"},
  {"name"=>"Linda Lin/林佩璇", "user_number"=>"TW0464", "department"=>"MKT"},
  {"name"=>"Mandy Peng/彭郁嵐", "user_number"=>"TW0465", "department"=>"Admin"},
  {"name"=>"Mingyuan Cheng/鄭茗元", "user_number"=>"TW0463", "department"=>"OP"},
  {"name"=>"Violet Huang/黃榆鈞", "user_number"=>"TW0462", "department"=>"MS"}
]

new_users.each do |data|
  user = User.create_or_find_by(user_number: data['user_number'])
  user.update!(name: data['name'], department: data['department'])
end
puts 'finished importing new_users'

interns = [
  {"name"=>"Ira Wang/王薏雯", "user_number"=>"I038", "department"=>"MKT"},
  {"name"=>"Chadarat Phokhathanawat/葉名妙", "user_number"=>"I062", "department"=>"MKT"},
  {"name"=>"Silitha Kasiwong", "user_number"=>"I065", "department"=>"MS"},
  {"name"=>"Grace Huang/黃品瑄", "user_number"=>"I070", "department"=>"MS"},
  {"name"=>"Lan Huong/阮氏蘭香", "user_number"=>"I072", "department"=>"MS"},
  {"name"=>"Joseph Ding/丁明聰", "user_number"=>"I073", "department"=>"MKT"},
  {"name"=>"Chatdanai Atchariyatham/安凱達", "user_number"=>"I075", "department"=>"MS"},
  {"name"=>"Jay Lee/李紹銘", "user_number"=>"I076", "department"=>"MS"},
  {"name"=>"Isabel Chuong/張弘春", "user_number"=>"I077", "department"=>"MS"},
  {"name"=>"Sanni Lee/李佩珊", "user_number"=>"I078", "department"=>"MS"},
  {"name"=>"Nhu Hoang/黃素茹", "user_number"=>"I079", "department"=>"MS"},
  {"name"=>"Carolyn Lin/林怡璇", "user_number"=>"I080", "department"=>"MS"},
  {"name"=>"Paisatchayakul Napat（Cherry）/麗美梅", "user_number"=>"I081", "department"=>"MKT"},
  {"name"=>"Ken Tsai/蔡竟恆", "user_number"=>"I082", "department"=>"MS"},
  {"name"=>"Anita Liu/劉芝瑋", "user_number"=>"I083", "department"=>"MKT"},
  {"name"=>"Grace Tsai/蔡沛恩", "user_number"=>"I084", "department"=>"MS"},
  {"name"=>"John Wu/吳嘉恩", "user_number"=>"I085", "department"=>"MS"},
  {"name"=>"Yvonne Lin/林毓芳", "user_number"=>"I086", "department"=>"OP"},
  {"name"=>"Catherine Liu/劉于瑄", "user_number"=>"I088", "department"=>"QA"},
  {"name"=>"Hsuan Fang/方綵暄", "user_number"=>"I089", "department"=>"QA"}
]

interns.each do |data|
  user = User.create_or_find_by(user_number: data['user_number'])
  user.update!(name: data['name'], department: data['department'])
end
puts 'finished importing intern'

drawable_prizes = [
  {'key' => '1','title' => '一獎(iphone 12)', 'quantity' => 1, 'bulk' => 1},
  {'key' => '2','title' => '二獎(dyson)', 'quantity' => 3, 'bulk' => 1},
  {'key' => '3','title' => '三獎(住宿券）', 'quantity' => 6, 'bulk' => 1},
  {'key' => '4','title' => '四獎(air pods)', 'quantity' => 10, 'bulk' => 2},
  {'key' => '4-2','title' => '四獎(電動牙刷)', 'quantity' => 5, 'bulk' => 5},
  {'key' => '5','title' => '五獎(apple 禮品卡)', 'quantity' => 15, 'bulk' => 3},
  {'key' => '5-2','title' => '五獎(小米吸塵器) 3名', 'quantity' => 3, 'bulk' => 3},
  {'key' => '5-3','title' => '五獎(小米吸塵器) 4名', 'quantity' => 4, 'bulk' => 4},
  {'key' => '6','title' => '六獎(現金$3000)', 'quantity' => 25, 'content' => '$3,000', 'bulk' => 5},
  {'key' => '11','title' => '加碼', 'quantity' => 10, 'content' => '', 'bulk' => 1, 'limited' => false}
]
drawable_prizes.each do |data|
  prize = Prize.create_or_find_by(key: data['key'])
  prize.update!(title: data['title'], quantity: data['quantity'], content: data['content'], drawable: true, bulk: data['bulk'], limited: data['limited'])
end
puts 'finished importing drawable_prizes'

undrawable_prizes = [
  {'key' => '7','title' => '加碼小遊戲', 'quantity' => 5},
  {'key' => '8','title' => '服裝獎', 'quantity' => 1, 'content' => '$5,000'},
  {'key' => '9','title' => '正職參加獎', 'quantity' => 216, 'content' => '$2,000'},
  {'key' => '10','title' => 'intern 獎', 'quantity' => 19, 'content' => '$1,000'}
]
undrawable_prizes.each do |data|
  prize = Prize.create_or_find_by(key: data['key'])
  prize.update!(title: data['title'], quantity: data['quantity'], content: data['content'], drawable: false)
end
puts 'finished importing undrawable_prizes'